"""Type stubs for ATKConnection — declares monkey-patched factory methods."""

from __future__ import annotations

from typing import Any, Generator

from atk.connect.access import AccessBuilder, AccessMultiBuilder
from atk.connect.cat import AdvCatBuilder
from atk.connect.constellation import ConstellationCreator, WalkerBuilder
from atk.connect.coverage import CoverageBuilder, CoverageMultiBuilder
from atk.connect.facility import FacilityBuilder
from atk.connect.reports import ReportResult
from atk.connect.satellite import SatelliteBuilder
from atk.connect.scenario import ScenarioBuilder
from atk.connect.vgt import VectorToolBuilder

class ATKConnection:
    con_id: int
    host: str
    port: int
    is_connected: bool

    def __init__(self, con_id: int, host: str, port: int) -> None: ...
    def send(self, command: str, obj_path: str = "*", param: str = "") -> Any: ...
    def wait_ready(self, timeout: float = ..., interval: float = ...) -> bool: ...
    def send_retry(self, command: str, obj_path: str = "*", param: str = "", retries: int = ..., interval: float = ...) -> Any: ...
    def close(self) -> None: ...

    # Factory methods injected by _patch_connection() at import time
    def create_scenario(self, name: str) -> ScenarioBuilder: ...
    def create_satellite(self, name: str, **kwargs: Any) -> SatelliteBuilder: ...
    def create_facility(self, name: str, lat: float = ..., lon: float = ..., height: float = ...) -> FacilityBuilder: ...
    def mcs_builder(self, sat_path: str) -> McsBuilder: ...
    def create_coverage(self, name: str) -> CoverageBuilder: ...
    def constellation_builder(self, name: str) -> WalkerBuilder: ...
    def quick_report(self, obj_path: str, style: str, time_period: str = "*") -> ReportResult: ...
    def report_rm(self, obj_path: str, style: str, time_period: str = "*") -> ReportResult: ...
    def access_builder(self) -> AccessBuilder: ...
    def access_multi(self) -> AccessMultiBuilder: ...
    def coverage_multi(self) -> CoverageMultiBuilder: ...
    def vector_tool(self, parent_object: str) -> VectorToolBuilder: ...
    def create_adv_cat(self, name: str) -> AdvCatBuilder: ...
    def constellation_creator(self) -> ConstellationCreator: ...
    def quick_report_create(self, name: str) -> Any: ...
    def quick_report_add(self, name: str, style: str, obj_path: str, from_object: str | None = ...) -> Any: ...
    def quick_report_list(self) -> list[str]: ...
    def quick_report_get(self, name: str) -> list[str]: ...
    def exec_report_create(self, obj_path: str, style: str, file: str | None = ..., start: str | None = ..., stop: str | None = ..., time_step: float | None = ...) -> Any: ...
    def exec_report_rm(self, obj_path: str, style: str, start: str | None = ..., stop: str | None = ..., time_step: float | None = ...) -> ReportResult: ...

class ATKConnectionManager:
    host: str
    port: int
    timeout: float
    retries: int
    backoff: float
    def __init__(
        self,
        host: str = ...,
        port: int = ...,
        timeout: float = ...,
        retries: int = ...,
        backoff: float = ...,
    ) -> None: ...
    def connect(self) -> ATKConnection: ...

def connect(
    host: str = ...,
    port: int = ...,
    timeout: float = ...,
    retries: int = ...,
    backoff: float = ...,
) -> Generator[ATKConnection, None, None]: ...
